#baseurl = "https://fundon.github.io/"
#baseurl = "./"
baseurl = "https://fundon..me"
canonifyUrls = true
copyright = "Copyright (c) 2015, Fangdun Cai; all rights reserved."
title = "Fangdun Cai"
description = ""
disqusShortname = "fundon"
hasCJKLanguage = true
languageCode = "en-us"
theme = "robots"
Paginate = 7
MetaDataFormat = "yaml"

[taxonomies]
  category = "categories"
  doc = "doc"
  tag = "tags"

[indexes]
  tag = "tags"
  category = "categories"

[params]
  author = "fundon"
  description = "Fundon's Moving Castle"
  twitter = "_fundon"
  github = "fundon"
  fullname = "Fangdun Cai"
  trackingId = "UA-59772344-1"
  tempmap = []

[Blackfriday]
  plainIdAnchors = true

[[menu.main]]
    name = "All Topics"
    url = "/tags"
    identifier = "tags"
    weight = -100

[[menu.main]]
    name = "Design"
    url = "/design"
    identifier = "design"
    weight = -80

[[menu.main]]
    name = "Web"
    url = "/web"
    identifier = "web"
    weight = -60

[[menu.main]]
    name = "iOS"
    url = "/ios"
    identifier = "iOS"
    weight = -40

[[menu.main]]
    name = "Feed"
    url = "/index.xml"
    identifier = "feed"
    weight = -20
