baseurl = "https://fundon.github.io/"
theme = "NexT"
title = "Fangdun Cai"
description = ""
languageCode = "en-us"
disqusShortname = "fundon"
copyright = "Copyright (c) 2015, Fangdun Cai; all rights reserved."
Paginate = 7
canonifyUrls = true

MetaDataFormat = "yaml"

[params]
  author = "fundon"
  description = "Fundon's Moving Castle"
  twitter = "_fundon"
  github = "fundon"

[Blackfriday]
  plainIdAnchors = true

[indexes]
  tag = "tags"
  category = "categories"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = -100

[[menu.main]]
    name = "Blog"
    url = "/Blog"
    identifier = "archives"
    weight = -80

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -60

[[menu.main]]
    name = "Feed"
    url = "/index.xml"
    weight = -40