#baseurl = "https://fundon.github.io/"
baseurl = "./"
title = "Fangdun Cai"
description = ""
languageCode = "en-us"
disqusShortname = "fundon"
copyright = "Copyright (c) 2015, Fangdun Cai; all rights reserved."
Paginate = 7
canonifyUrls = true
theme = "robots"

MetaDataFormat = "yaml"

[params]
  author = "fundon"
  description = "Fundon's Moving Castle"
  twitter = "_fundon"
  github = "fundon"
  fullname = "Fangdun Cai"

[params.googleAnalytics]
  trackingId = "UA-59772344-1"

[Blackfriday]
  plainIdAnchors = true

[indexes]
  tag = "tags"
  category = "categories"

[[menu.main]]
    name = "All Topics"
    url = "/tags"
    identifier = "tags"
    weight = -100

[[menu.main]]
    name = "Design"
    url = "/design"
    identifier = "design"
    weight = -80

[[menu.main]]
    name = "Web"
    url = "/web"
    identifier = "web"
    weight = -60

[[menu.main]]
    name = "iOS"
    url = "/ios"
    identifier = "iOS"
    weight = -40

[[menu.main]]
    name = "Feed"
    url = "/index.xml"
    identifier = "feed"
    weight = -20
