baseurl = "https://fundon.github.io/"
title = "Fangdun Cai"
description = ""
languageCode = "en-us"
disqusShortname = "fundon"
copyright = "Copyright (c) 2015, Fangdun Cai; all rights reserved."
metaDataFormat = "yaml"

twitter = "_fundon"

[author]
  name = "fundon"

[indexes]
  tag = "tags"
  topic = "topics"